# Generated by Django 2.1.7 on 2019-05-02 10:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='type_of_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_type_of_currency', to='account.TypeOfCurrency'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
