# Generated by Django 2.1.7 on 2019-04-20 20:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('type_of_currency', models.CharField(max_length=20)),
                ('count', models.DecimalField(blank=True, decimal_places=2,
                                              max_digits=12)),
                ('created',
                 models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField()),
                ('user', models.ForeignKey(blank=True,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           related_name='user_account',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
